[application]

[web.app]
base_path = "tortus-exe.github.io"

# HTML title tag content
title = "tortus-exe-github-io"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
